name: Deploy Azure Static Web App

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infrastructure/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  repository_dispatch:
    types: [infrastructure-deployed]
  workflow_run:
    workflows:
      - Deploy Infrastructure and App
    types:
      - completed
  workflow_dispatch:
  workflow_call:

jobs:
  build-only:
    name: Build Application (Pull Request)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install or update npm packages
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

  build-and-deploy-app:
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install or update npm packages
        run: npm install

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Deploy to Static Web App
        run: |
          npx @azure/static-web-apps-cli deploy \
            --app-location . \
            --api-location "" \
            --output-location build \
            --deployment-token "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" \
            --env production

  validate-deployment:
    name: Validate Deployment
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build-and-deploy-app
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check Deployment Status
        run: |
          APP_URL=$(az staticwebapp show \
            --name swa-thestratbook-prod \
            --query "defaultHostname" -o tsv)

          echo "Application deployed to: https://$APP_URL"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://$APP_URL)

          if [ $HTTP_STATUS -eq 200 ]; then
            echo "✅ Deployment validated successfully!"
          else
            echo "❌ Deployment validation failed! Status code: $HTTP_STATUS"
            exit 1
          fi