name: Deploy Infrastructure and App

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Templates
        run: |
          az deployment sub create \
            --name github-deployment \
            --location westeurope \
            --template-file infrastructure/main.bicep \
            --parameters location=westeurope \
                         resourceGroupName=rg-thestratbook-prod \
                         staticWebAppName=swa-thestratbook-prod \
                         budgetAmount=10 \
                         primaryDomain=thestratbook.com

  build-and-deploy-app:
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Deploy to Static Web App
        run: |
          npx @azure/static-web-apps-cli deploy \
            --app-location . \
            --api-location "" \
            --output-location build \
            --deployment-token ${{ secrets.STATIC_WEB_APP_TOKEN }} \
            --env production

  validate-deployment:
    name: Validate Deployment
    runs-on: ubuntu-latest
    needs: build-and-deploy-app
    steps:
      - name: Check Deployment Status
        run: |
          APP_URL=$(az staticwebapp show \
            --name swa-thestratbook-prod \
            --query "defaultHostname" -o tsv)

          echo "Application deployed to: https://$APP_URL"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://$APP_URL)

          if [ $HTTP_STATUS -eq 200 ]; then
            echo "✅ Deployment validated successfully!"
          else
            echo "❌ Deployment validation failed! Status code: $HTTP_STATUS"
            exit 1
          fi